### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by sornen** [budimanjojo/tmux.fish#10]
On macOS opening a new terminal (command N) results in a copy of the old terminal and all subsequent commands in the new terminal are duplicated in the old terminal and vice a versa. This can be fixed by 

`set -q fish_tmux_autoconnect || set fish_tmux_autoconnect false # true`

**Comment by budimanjojo** [comment]
Yeah `fish_tmux_autoconnect` is set to `true` by default as stated in the `README`. You can add the line above to your `config.fish` to override it.

I will close this issue as this is expected behavior, thank you for reporting!

**Comment by sornen** [comment]
But for someone new to tmux.fish it is not obvious that you should do this with macOS, whereas with linux I had no problems with the standard installation.  I only found a fix for the problem by going through various combination to find out what true or false worked. Thus, I think it may be useful, if for a macOS installation the default was false or at least in the README it stated that for macOS the `fish_tmux_autoconnect` should be set to false, to get correct terminal behavior. Anyhow ty for your work on this. Just changed over to fish from bash and tmux.fish helps.

**Comment by budimanjojo** [comment]
Sorry but I don't understand how is this MacOS only problem. Is MacOS acting weird with tmux when opening a new terminal? The idea of using tmux is you only open one terminal and create as many new windows or pane as you like on that one terminal. And if you open a new terminal and attach to the already opened tmux session then you will have mirrored terminal and it's expected on both MacOS and Linux.

But you're correct that the default to autoconnect and autostart is not for everyone which I stated in the README about the difference from the zsh version. It's my personal preference to only use one tmux session and not opening new terminal but open new tmux window in the same terminal instead.

**Comment by sornen** [comment]
Well if that is the expected behavior then it is not occurring with my Linux PC but is with macOS. The reason that the default behavior is not wanted by me is that in separate workspaces it is preferable to have separate terminals. Even in the same workspace the default behavior has no utility in that having a mirrored terminal is of no use and as you point out the point of tmux is to use panes. But if for some reason another terminal was wanted perhaps on a separate screen, I run a tiling window manager, then again I feel the default behavior should not be to mirror the terminal, but perhaps there is some utility to this that I am missing.

**Comment by budimanjojo** [comment]
It's weird that in your Linux PC it's not doing that when it should.

And yes, like I mentioned before, the default behavior is my preference and it's not for everybody. But as the behavior is configureable by setting the env variable and you're free to set it however you like. I don't think changing the default behavior of the tool is a good idea as it will be shocking for other people those are already using this tool and expect the current default behavior.

**Comment by sornen** [comment]
Thanks for your help.
