### ISSUE TITLE
ctrl+c close terminal

### ISSUE THREAD

**Issue by blueray453** [budimanjojo/tmux.fish#6]
if I type <kbd>Ctrl + C</kbd> to send SIGINT (I think in fish <kbd>Ctrl + C</kbd> is bound to `cancel-commandline`) the whole terminal closes.

In normal terminal, it should do nothing if there is no running process, else kill that process.

**Comment by budimanjojo** [comment]
Not sure why it's happening but this plugin is just calling `tmux` on startup and do nothing else. So I'm pretty sure it's not what causing that problem
